### PR TITLE
rust2rpm: disable development-only feature for regenerating sources

### PR DESCRIPTION
**Pull request by HuijingHei**
See https://src.fedoraproject.org/rpms/rust-ignition-config/pull-request/3

### CODE REVIEW

**Comment by HuijingHei** [comment]
Create new spec with this patch, the development-only features are disabled as expected, see following results:

```
]# rust2rpm -s ignition-config
• Generated: rust-ignition-config.spec
]# wget https://src.fedoraproject.org/rpms/rust-ignition-config/raw/rawhide/f/rust-ignition-config.spec
]# diff rust-ignition-config.spec rust-ignition-config.spec.1
1c1
< # Generated by rust2rpm 26
---
> # Generated by rust2rpm 23
8c8
< Version:        0.4.0
---
> Version:        0.3.0
14a15,16
> # Disable development-only feature for regenerating sources
> Patch0:         ignition-config-fix-metadata.diff
16c18
< BuildRequires:  cargo-rpm-macros >= 24
---
> BuildRequires:  rust-packaging >= 21
50c52
< %autosetup -n %{crate}-%{version} -p1
---
> %autosetup -n %{crate}-%{version_no_tilde} -p1
```

**Comment by HuijingHei** [comment]
Not sure if we still need `Patch0: ignition-config-fix-metadata.diff` to remove the build-dependencies crates in `Cargo.toml`,  anyway to test this?

**Comment by prestist** [comment]
@HuijingHei Yeah I think this will work; regarding testing, I think the test is the .spec file should be disabling features using '--feature' or something like that. 

So the main test is that we have features disabled "listed in the generated spec file"
That should then make the .patch file and the 'patch 0' line obsolete.

**Comment by HuijingHei** [comment]
Thanks @prestist for the confirmation!

**Review by prestist — APPROVED** [review]
LGTM

**Pull request merged**
